name: "CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          package-manager-cache: false
          registry-url: "https://registry.npmjs.org"
      - run: |
          pnpm install --frozen-lockfile
          pnpm lint
          pnpm test
          pnpm build
          pnpm run test:dist
