name: "CI"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          package-manager-cache: false
          registry-url: "https://registry.npmjs.org"
      - run: |
          npm install --global pnpm@latest
          pnpm install --no-frozen-lockfile
          pnpm lint
          pnpm test
          pnpm build
          pnpm run test:dist
